#!/usr/bin/env php
<?php

define('APP_ROOT', __DIR__);
define('OCTANE_START', microtime(true));

require_once APP_ROOT . '/vendor/autoload.php';

/** @var Horizon\Arch\Application $app */
$app = require_once APP_ROOT . '/boot/app.php';

exit($app->runCli($argv));
